apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
data:
  AUTH_SERVICE_INTERNAL_TOKEN: "kXCvxBXJk9XL+h1oWGZa2gSRXFXNi78aBGON/vWc/NQ="
  AUTH_SERVICE_MASTER_KEY: "4/NI5ZVXCJjvLHiTVfPB1NSPThY5ESxTBhXJiE1Y8mk="
