apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms3-dev-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ms3-system/ms3-fleet
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ms3-dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
