apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms3-production-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ms3-system/ms3-fleet
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ms3-prod
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
