apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: api-service-config
    literals:
      - API_SERVICE_METADATA_URL=http://metadata-service.ms3-dev.svc.cluster.local:8083
      - API_SERVICE_DATA_URL=http://data-service.ms3-dev.svc.cluster.local:8081
      - API_SERVICE_AUTH_URL=http://auth-service.ms3-dev.svc.cluster.local:8082

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: api-service
      app.kubernetes.io/part-of: ms3
