apiVersion: v1
kind: Secret
metadata:
  name: api-service-secret
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: ms3
data:
  API_SERVICE_INTERNAL_TOKEN: "kXCvxBXJk9XL+h1oWGZa2gSRXFXNi78aBGON/vWc/NQ="
