apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ms3-prod

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - name: api-service-config
    behavior: merge
    literals:
      - API_SERVICE_METADATA_URL=http://metadata-service.ms3-prod.svc.cluster.local:8083
      - API_SERVICE_DATA_URL=http://data-service.ms3-prod.svc.cluster.local:8081
      - API_SERVICE_AUTH_URL=http://auth-service.ms3-prod.svc.cluster.local:8082

images:
  - name: ghcr.io/ms3-system/api-service
    digest: sha256:49489f6bb64ca72b4f4735b98a294840dd79d952237eb305578d46bd31249d5d
  - name: ghcr.io/ms3-system/data-service
    digest: sha256:787b266a01314623fe6479e1f1848a3568609b53366252405e9da9039b210de0
  - name: ghcr.io/ms3-system/auth-service
    digest: sha256:6f6b9596cc735d3e04b27cbb662d757a4ba602714b9c0cedca754ab48dfb8ef2
  - name: ghcr.io/ms3-system/metadata-service
    digest: sha256:6b7d63af4a501cfd13a73122e9ffbf7bf2e0bc403b971fa443e68a2b11bc87d7

labels:
  - includeSelectors: true
    pairs:
      environment: prod
      app.kubernetes.io/part-of: ms3
