apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app.kubernetes.io/name: data-service
    app.kubernetes.io/part-of: ms3
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: data-service
      app.kubernetes.io/part-of: ms3
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None
