apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  labels:
    app.kubernetes.io/name: metadata-service
    app.kubernetes.io/part-of: ms3
spec:
  selector:
    app.kubernetes.io/name: metadata-service
    app.kubernetes.io/part-of: ms3
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  clusterIP: None
