name: Run Jobs on PR
on: pull_request
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: cncf/prow-github-actions@v2
        with:
          jobs: lgtm
          github-token: "${{ secrets.GITHUB_TOKEN }}"
